# docker-compose.yml
version: "3.3"
services:
  frontend:
    build: ./public
    ports:
      - "5002:5002"
    environment:
      - HTTPS=false
    restart: unless-stopped

  bank:
    build: ./bank
    ports:
      - "6002:6002"
    environment:
      - HTTPS=false
      - STORAGE_DIR=/data/storage
    volumes:
      - projects:/data/storage
    restart: unless-stopped

volumes:
    projects:
